# Generated by Django 5.0.6 on 2024-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Direccion desconocida', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(default='8090003333', max_length=15),
            preserve_default=False,
        ),
    ]
