# Generated by Django 5.0.6 on 2024-06-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbs', '0002_user_address_user_cell_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
